import { ethers, network } from "hardhat";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";

type ContractsMap = Record<string, string>;

function ensureDir(p: string) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function loadContractsMap(filePath: string): ContractsMap {
  if (!existsSync(filePath)) return {};
  return JSON.parse(readFileSync(filePath, "utf-8")) as ContractsMap;
}

function writeFrontendContractsTs(filePath: string, map: ContractsMap) {
  const entries = Object.entries(map)
    .sort((a, b) => Number(a[0]) - Number(b[0]))
    .map(([chainId, addr]) => `  "${chainId}": "${addr}"`)
    .join(",\n");

  const content = `// Auto-generated by scripts/deploy.ts
export const CONTRACTS: Record<string, string> = {
${entries}
};
`;
  writeFileSync(filePath, content);
}

async function main() {
  const net = await ethers.provider.getNetwork();
  const chainId = net.chainId.toString();
  const networkName = network.name; // "localhost"

  const initialCandidates = ["Alice", "Bob", "Emma"];

  const Voting = await ethers.getContractFactory("Voting");
  const voting = await Voting.deploy(initialCandidates);
  await voting.waitForDeployment();

  const address = await voting.getAddress();
  console.log(`Voting deployed to ${address} on ${networkName} (chainId=${chainId})`);

  // 1) Save deployment info
  const deploymentPath = path.join(__dirname, "..", `deployment.${networkName}.json`);
  writeFileSync(deploymentPath, JSON.stringify({ address, chainId, networkName }, null, 2));

  // 2) Update frontend config map (chainId -> address)
  const frontendConfigDir = path.join(__dirname, "..", "frontend", "src", "config");
  ensureDir(frontendConfigDir);

  const contractsTs = path.join(frontendConfigDir, "contracts.ts");
  const existingMap = loadContractsMap(path.join(frontendConfigDir, "contracts.json"));

  const newMap: ContractsMap = { ...existingMap, [chainId]: address };

  // Save json (easy for scripts) and ts (for import into React)
  writeFileSync(path.join(frontendConfigDir, "contracts.json"), JSON.stringify(newMap, null, 2));
  writeFrontendContractsTs(contractsTs, newMap);

  console.log("Updated frontend config:", contractsTs);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});